#!/usr/bin/env python
# coding: utf-8

def build(ctx):
    lc_inc_dir = ctx.path.parent.find_dir('latcommon/include')
    inc_dir = ctx.path.parent.find_dir('include')
    src_dir = ctx.path

    #ctx(features='cxx cxxprogram test',
    #        source='TestSomething.cc',
    #        includes=[inc_dir, lc_inc_dir],
    #        lib=ctx.env.LIB_NTL,
    #        stlib=ctx.env.STLIB_NTL,
    #        use=['latmrg' + ctx.env.LATCOMMON_SUFFIX, 'latcommon' + ctx.env.LATCOMMON_SUFFIX],
    #        target='TestLacunary' + ctx.env.LATCOMMON_SUFFIX)

    from waflib.Tools import waf_unit_test
    ctx.add_post_fun(waf_unit_test.summary)
