#!/usr/bin/env python
# coding: utf-8

def build(ctx):
    lc_inc_dir = ctx.path.parent.find_dir('latcommon/include')
    inc_dir = ctx.path.parent.find_dir('include')
    src_dir = ctx.path

    ctx(features='cxx cxxstlib',
            source=src_dir.ant_glob('*.cc'),
            includes=[inc_dir, lc_inc_dir],
            target='latmrg' + ctx.env.LATCOMMON_SUFFIX,
            install_path='${LIBDIR}')

    # header files
    for inc in inc_dir.ant_glob('**/*.h'):
        ctx.install_files('${INCLUDEDIR}/' + inc.parent.path_from(inc_dir), inc)
